export const campaignCards = (city = "your city") => [
  {
    title: "Flat ₹150 OFF",
    subtitle: "On First Order",
    desc: "Use code WELCOME150 and enjoy premium meals delivered fresh to your doorstep.",
    badge: "LIMITED",
    icon: "🎉",
    button: "Order Now",
    gradient: "from-orange-500 via-red-500 to-pink-500",
    glow: "bg-orange-400/20",
  },
  {
    title: `Trending in ${city}`,
    subtitle: "Top Rated Kitchens",
    desc: "Discover the most-loved restaurants and viral dishes around you.",
    badge: "HOT",
    icon: "🔥",
    button: "Explore",
    gradient: "from-[#ff7a18] via-[#ff5f6d] to-[#ffc371]",
    glow: "bg-white/10",
  },
  {
    title: "Free Delivery",
    subtitle: "No Extra Charges",
    desc: "Enjoy unlimited free delivery on selected premium restaurants nearby.",
    badge: "FREE",
    icon: "🛵",
    button: "Claim Now",
    gradient: "from-slate-900 via-slate-800 to-black",
    glow: "bg-orange-500/10",
  },
  {
    title: "Buy 1 Get 1",
    subtitle: "Weekend Specials",
    desc: "Double the happiness with exclusive BOGO deals from partner brands.",
    badge: "BOGO",
    icon: "🍔",
    button: "Grab Deal",
    gradient: "from-yellow-400 via-orange-500 to-red-500",
    glow: "bg-white/10",
  },
  {
    title: "Late Night Cravings",
    subtitle: "Open Till 3 AM",
    desc: "Fresh food delivered even after midnight from trusted kitchens.",
    badge: "24/7",
    icon: "🌙",
    button: "See Options",
    gradient: "from-[#111827] via-[#1f2937] to-[#374151]",
    glow: "bg-indigo-400/10",
  },
];